using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SimpleStructuredBinaryFormat.Binding.Generator;

[Microsoft.CodeAnalysis.Generator(LanguageNames.CSharp)]
public sealed class SsbfBindingGenerator : IIncrementalGenerator
{
    private const string SerializableAttr    = "SimpleStructuredBinaryFormat.Binding.SsbfSerializableAttribute";
    private const string PropertyAttr        = "SimpleStructuredBinaryFormat.Binding.SsbfPropertyAttribute";
    private const string IgnoreAttr          = "SimpleStructuredBinaryFormat.Binding.SsbfIgnoreAttribute";
    private const string NameConventionAttr  = "SimpleStructuredBinaryFormat.Binding.SsbfNameConventionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SerializableAttr,
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static s => s is not null);

        context.RegisterSourceOutput(targets, Emit);
    }

    // -------------------------------------------------------------------------
    // Per-type emission
    // -------------------------------------------------------------------------

    private static void Emit(SourceProductionContext ctx, INamedTypeSymbol type)
    {
        var members = CollectMembers(type);

        var ns           = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();
        var typeName     = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeKind     = type.IsValueType ? "struct" : (type.IsRecord ? (type.IsValueType ? "record struct" : "record") : "class");
        var fileName     = Escape(type.ToDisplayString()) + "_SsbfBinder.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SimpleStructuredBinaryFormat;");
        sb.AppendLine("using SimpleStructuredBinaryFormat.Binding;");
        sb.AppendLine();

        if (ns is not null) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }

        // Partial type declaration — extends the user's own partial class/struct/record
        sb.AppendLine($"    partial {typeKind} {typeName}");
        sb.AppendLine("    {");

        // Static convenience property
        sb.AppendLine($"        /// <summary>The source-generated <see cref=\"ISsbfBinder{{T}}\"/> for <see cref=\"{typeName}\"/>.</summary>");
        sb.AppendLine($"        public static SsbfBinder Binder => SsbfBinder.Instance;");
        sb.AppendLine();

        // Nested binder class
        sb.AppendLine($"        /// <summary>Source-generated <see cref=\"ISsbfBinder{{T}}\"/> for <see cref=\"{typeName}\"/>.</summary>");
        sb.AppendLine($"        public sealed class SsbfBinder : ISsbfBinder<{fullTypeName}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            public static readonly SsbfBinder Instance = new SsbfBinder();");
        sb.AppendLine();

        EmitSerialize(sb, fullTypeName, members);
        sb.AppendLine();
        EmitDeserialize(sb, fullTypeName, type, members);

        sb.AppendLine("        }"); // end SsbfBinder
        sb.AppendLine("    }");     // end partial type

        if (ns is not null) sb.AppendLine("}");

        ctx.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // -------------------------------------------------------------------------
    // Serialize
    // -------------------------------------------------------------------------

    private static void EmitSerialize(StringBuilder sb, string fullTypeName, List<MemberInfo> members)
    {
        sb.AppendLine($"            public void Serialize({fullTypeName} value, SsbfWriter writer)");
        sb.AppendLine("            {");
        sb.AppendLine("                writer.WriteStartObject();");
        foreach (var m in members)
        {
            sb.AppendLine($"                writer.WritePropertyName(\"{m.Key}\");");
            EmitWriteValue(sb, $"value.{m.MemberName}", m.Kind, m.FullTypeName, m.ElemKind, m.ElemFullTypeName, 4);
        }
        sb.AppendLine("                writer.WriteEndObject();");
        sb.AppendLine("            }");
    }

    private static void EmitWriteValue(StringBuilder sb, string expr, TKind kind, string fullType,
        TKind elemKind, string? elemFull, int indent)
    {
        var p = Pad(indent);
        switch (kind)
        {
            case TKind.Bool:   sb.AppendLine($"{p}writer.WriteBoolean({expr});"); break;
            case TKind.SByte:  sb.AppendLine($"{p}writer.WriteSByte({expr});"); break;
            case TKind.Short:  sb.AppendLine($"{p}writer.WriteShort({expr});"); break;
            case TKind.Int:    sb.AppendLine($"{p}writer.WriteInteger({expr});"); break;
            case TKind.Long:   sb.AppendLine($"{p}writer.WriteLong({expr});"); break;
            case TKind.Byte:   sb.AppendLine($"{p}writer.WriteByte({expr});"); break;
            case TKind.UShort: sb.AppendLine($"{p}writer.WriteUShort({expr});"); break;
            case TKind.UInt:   sb.AppendLine($"{p}writer.WriteUInteger({expr});"); break;
            case TKind.ULong:  sb.AppendLine($"{p}writer.WriteULong({expr});"); break;
            case TKind.Half:   sb.AppendLine($"{p}writer.WriteHalf({expr});"); break;
            case TKind.Float:  sb.AppendLine($"{p}writer.WriteSingle({expr});"); break;
            case TKind.Double: sb.AppendLine($"{p}writer.WriteDouble({expr});"); break;
            case TKind.String:
                sb.AppendLine($"{p}if ({expr} is null) writer.WriteNull(); else writer.WriteString({expr});");
                break;
            case TKind.ByteArray:
                sb.AppendLine($"{p}if ({expr} is null) writer.WriteNull(); else writer.WriteByteArray({expr});");
                break;
            case TKind.NullablePrimitive:
                sb.AppendLine($"{p}if ({expr} is null) writer.WriteNull();");
                sb.AppendLine($"{p}else");
                sb.AppendLine($"{p}{{");
                EmitWriteValue(sb, $"{expr}.Value", elemKind, elemFull ?? fullType, TKind.Unknown, null, indent + 1);
                sb.AppendLine($"{p}}}");
                break;
            case TKind.List:
                sb.AppendLine($"{p}if ({expr} is null) {{ writer.WriteNull(); }}");
                sb.AppendLine($"{p}else");
                sb.AppendLine($"{p}{{");
                sb.AppendLine($"{p}    writer.WriteStartArray();");
                sb.AppendLine($"{p}    foreach (var __item in {expr})");
                sb.AppendLine($"{p}    {{");
                EmitWriteValue(sb, "__item", elemKind, elemFull ?? "object", TKind.Unknown, null, indent + 2);
                sb.AppendLine($"{p}    }}");
                sb.AppendLine($"{p}    writer.WriteEndArray();");
                sb.AppendLine($"{p}}}");
                break;
            case TKind.Nested:
                // elemFull holds the simple (unqualified) type name for Nested — see Classify()
                var nestedBinder = Escape(elemFull ?? Strip(fullType)) + ".SsbfBinder";
                sb.AppendLine($"{p}if ({expr} is null) writer.WriteNull();");
                sb.AppendLine($"{p}else new {nestedBinder}().Serialize({expr}, writer);");
                break;
            default:
                sb.AppendLine($"{p}// SSBF: unsupported type '{fullType}' — skipped");
                sb.AppendLine($"{p}writer.WriteNull();");
                break;
        }
    }

    // -------------------------------------------------------------------------
    // Deserialize
    // -------------------------------------------------------------------------

    private static void EmitDeserialize(StringBuilder sb, string fullTypeName, INamedTypeSymbol type,
        List<MemberInfo> members)
    {
        // Public entry-point — reads the opening StartObject itself
        sb.AppendLine($"            public {fullTypeName} Deserialize(SsbfReader reader)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!reader.Read() || reader.TokenType != SsbfTokenType.StartObject)");
        sb.AppendLine("                    throw new InvalidOperationException(\"Expected StartObject token\");");
        sb.AppendLine("                return DeserializeFromStartObject(reader);");
        sb.AppendLine("            }");
        sb.AppendLine();
        // Internal entry-point — called when reader is already positioned on StartObject
        sb.AppendLine($"            internal {fullTypeName} DeserializeFromStartObject(SsbfReader reader)");
        sb.AppendLine("            {");

        foreach (var m in members)
            sb.AppendLine($"                {m.FullTypeName} __{m.MemberName} = {DefaultExpr(m.Kind)};");

        sb.AppendLine();
        sb.AppendLine("                while (reader.Read() && reader.TokenType != SsbfTokenType.EndObject)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (reader.TokenType != SsbfTokenType.PropertyName)");
        sb.AppendLine("                        throw new InvalidOperationException(\"Expected PropertyName\");");
        sb.AppendLine("                    var __key = reader.GetPropertyName();");
        sb.AppendLine("                    switch (__key)");
        sb.AppendLine("                    {");

        foreach (var m in members)
        {
            sb.AppendLine($"                        case \"{m.Key}\":");
            EmitReadValue(sb, $"__{m.MemberName}", m.Kind, m.FullTypeName, m.ElemKind, m.ElemFullTypeName, 7);
            sb.AppendLine("                            break;");
        }

        sb.AppendLine("                        default:");
        sb.AppendLine("                            SkipValue(reader);");
        sb.AppendLine("                            break;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine();

        // Construction
        var ctor = type.IsRecord ? FindRecordCtor(type, members) : null;
        if (ctor is not null)
        {
            var args = string.Join(", ", ctor.Parameters.Select(p =>
            {
                var m = members.FirstOrDefault(x =>
                    string.Equals(x.MemberName, p.Name, System.StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(x.Key, p.Name, System.StringComparison.OrdinalIgnoreCase));
                return m is not null ? $"__{m.MemberName}" : "default!";
            }));
            sb.AppendLine($"                return new {fullTypeName}({args});");
        }
        else
        {
            sb.AppendLine($"                return new {fullTypeName}");
            sb.AppendLine("                {");
            foreach (var m in members)
                sb.AppendLine($"                    {m.MemberName} = __{m.MemberName},");
            sb.AppendLine("                };");
        }

        sb.AppendLine("            }");
        sb.AppendLine();

        // SkipValue helper
        sb.AppendLine("            private static void SkipValue(SsbfReader reader)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!reader.Read()) return;");
        sb.AppendLine("                if (reader.TokenType == SsbfTokenType.StartObject || reader.TokenType == SsbfTokenType.StartArray)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var __depth = 1;");
        sb.AppendLine("                    while (__depth > 0 && reader.Read())");
        sb.AppendLine("                    {");
        sb.AppendLine("                        if (reader.TokenType == SsbfTokenType.StartObject || reader.TokenType == SsbfTokenType.StartArray) __depth++;");
        sb.AppendLine("                        else if (reader.TokenType == SsbfTokenType.EndObject || reader.TokenType == SsbfTokenType.EndArray) __depth--;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
    }

    private static void EmitReadValue(StringBuilder sb, string target, TKind kind, string fullType,
        TKind elemKind, string? elemFull, int indent)
    {
        var p = Pad(indent);
        switch (kind)
        {
            case TKind.Bool:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetBoolean();");
                break;
            case TKind.SByte:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetSByte();");
                break;
            case TKind.Short:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetShort();");
                break;
            case TKind.Int:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetInteger();");
                break;
            case TKind.Long:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetLong();");
                break;
            case TKind.Byte:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetByte();");
                break;
            case TKind.UShort:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetUShort();");
                break;
            case TKind.UInt:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetUInteger();");
                break;
            case TKind.ULong:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetULong();");
                break;
            case TKind.Half:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetHalf();");
                break;
            case TKind.Float:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetSingle();");
                break;
            case TKind.Double:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? default : reader.GetDouble();");
                break;
            case TKind.String:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? null! : reader.GetString();");
                break;
            case TKind.ByteArray:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}{target} = reader.TokenType == SsbfTokenType.Null ? null! : reader.GetByteArray();");
                break;
            case TKind.NullablePrimitive:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}if (reader.TokenType == SsbfTokenType.Null) {{ {target} = null; }}");
                sb.AppendLine($"{p}else {{ {target} = {ReaderCall(elemKind)}; }}");
                break;
            case TKind.List:
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}if (reader.TokenType != SsbfTokenType.Null)");
                sb.AppendLine($"{p}{{");
                sb.AppendLine($"{p}    {target} = new {Strip(fullType)}();");
                sb.AppendLine($"{p}    while (reader.Read() && reader.TokenType != SsbfTokenType.EndArray)");
                sb.AppendLine($"{p}    {{");
                var call = ReaderCall(elemKind);
                if (call is not null)
                    sb.AppendLine($"{p}        if (reader.TokenType != SsbfTokenType.Null) {target}.Add({call});");
                else
                    sb.AppendLine($"{p}        // unsupported list element type '{elemFull}' — skipped");
                sb.AppendLine($"{p}    }}");
                sb.AppendLine($"{p}}}");
                break;
            case TKind.Nested:
                // elemFull holds the simple (unqualified) type name for Nested — see Classify()
                var nestedBinder = Escape(elemFull ?? Strip(fullType)) + ".SsbfBinder";
                sb.AppendLine($"{p}if (!reader.Read()) break;");
                sb.AppendLine($"{p}if (reader.TokenType == SsbfTokenType.Null) {{ {target} = default!; break; }}");
                sb.AppendLine($"{p}// reader is on StartObject — delegate to nested binder's inner entry point");
                sb.AppendLine($"{p}{target} = new {nestedBinder}().DeserializeFromStartObject(reader);");
                break;
            default:
                sb.AppendLine($"{p}SkipValue(reader); // unsupported type '{fullType}'");
                break;
        }
    }

    // -------------------------------------------------------------------------
    // Member collection
    // -------------------------------------------------------------------------

    private static List<MemberInfo> CollectMembers(INamedTypeSymbol type)
    {
        // Read the naming convention from [SsbfNameConvention], default to None.
        var conventionValue = type.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameConventionAttr)
            ?.ConstructorArguments.FirstOrDefault().Value;
        var convention = conventionValue is int cv ? cv : 0; // 0 = None

        var result = new List<MemberInfo>();
        foreach (var member in type.GetMembers())
        {
            if (member.IsStatic) continue;
            if (member.DeclaredAccessibility != Accessibility.Public) continue;
            if (member is IFieldSymbol { AssociatedSymbol: not null }) continue; // backing field

            ITypeSymbol memberType;
            string memberName;

            if (member is IPropertySymbol prop && !prop.IsIndexer
                && prop.GetMethod is not null && prop.SetMethod is not null)
            { memberType = prop.Type; memberName = prop.Name; }
            else if (member is IFieldSymbol field && !field.IsConst && !field.IsReadOnly)
            { memberType = field.Type; memberName = field.Name; }
            else continue;

            if (member.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttr))
                continue;

            // [SsbfProperty] wins; otherwise apply the type-level convention.
            var keyOverride = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == PropertyAttr)
                ?.ConstructorArguments.FirstOrDefault().Value as string;

            var key = keyOverride ?? ApplyConvention(memberName, convention);
            var (kind, ek, ef) = Classify(memberType);
            result.Add(new MemberInfo(memberName, key, kind,
                memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), ek, ef));
        }
        return result;
    }

    // NameConvention enum values (mirrored from Binding project — kept in sync by value)
    private const int ConventionNone             = 0;
    private const int ConventionPascalCase       = 1;
    private const int ConventionCamelCase        = 2;
    private const int ConventionSnakeCase        = 3;
    private const int ConventionScreamingSnake   = 4;
    private const int ConventionKebabCase        = 5;

    private static string ApplyConvention(string name, int convention)
    {
        switch (convention)
        {
            case ConventionPascalCase:     return ToPascalCase(name);
            case ConventionCamelCase:      return ToCamelCase(name);
            case ConventionSnakeCase:      return ToSnakeCase(name, '_', false);
            case ConventionScreamingSnake: return ToSnakeCase(name, '_', true);
            case ConventionKebabCase:      return ToSnakeCase(name, '-', false);
            default:                       return name; // None
        }
    }

    private static string ToPascalCase(string name)
    {
        if (name.Length == 0) return name;
        // If already PascalCase (first char upper), return as-is; otherwise uppercase first char.
        if (char.IsUpper(name[0])) return name;
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length == 0) return name;
        if (char.IsLower(name[0])) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>
    /// Converts a PascalCase or camelCase identifier to a word-separated form.
    /// Treats sequences of uppercase letters as acronyms (e.g. HTMLParser → html_parser).
    /// </summary>
    private static string ToSnakeCase(string name, char separator, bool upper)
    {
        if (name.Length == 0) return name;
        var sb = new StringBuilder(name.Length + 4);
        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            bool isUpper = char.IsUpper(c);
            if (isUpper && i > 0)
            {
                // Insert separator before an uppercase letter that follows a lowercase letter,
                // or before an uppercase letter that is followed by a lowercase letter
                // (handles acronyms: XMLParser → xml_parser, not x_m_l_parser).
                bool prevLower = char.IsLower(name[i - 1]);
                bool nextLower = i + 1 < name.Length && char.IsLower(name[i + 1]);
                if (prevLower || nextLower)
                    sb.Append(separator);
            }
            sb.Append(upper ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Type classification
    // -------------------------------------------------------------------------

    private enum TKind
    {
        Unknown,
        Bool, SByte, Short, Int, Long,
        Byte, UShort, UInt, ULong,
        Half, Float, Double,
        String, ByteArray,
        NullablePrimitive,
        List,
        Nested,
    }

    private static (TKind kind, TKind elemKind, string? elemFull) Classify(ITypeSymbol type)
    {
        // Nullable<T>
        if (type is INamedTypeSymbol { IsValueType: true, OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            var inner = nullable.TypeArguments[0];
            var (ik, _, _) = Classify(inner);
            return (TKind.NullablePrimitive, ik, inner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        var k = type.SpecialType switch
        {
            SpecialType.System_Boolean => TKind.Bool,
            SpecialType.System_SByte   => TKind.SByte,
            SpecialType.System_Int16   => TKind.Short,
            SpecialType.System_Int32   => TKind.Int,
            SpecialType.System_Int64   => TKind.Long,
            SpecialType.System_Byte    => TKind.Byte,
            SpecialType.System_UInt16  => TKind.UShort,
            SpecialType.System_UInt32  => TKind.UInt,
            SpecialType.System_UInt64  => TKind.ULong,
            SpecialType.System_Single  => TKind.Float,
            SpecialType.System_Double  => TKind.Double,
            SpecialType.System_String  => TKind.String,
            _ => TKind.Unknown
        };
        if (k != TKind.Unknown) return (k, TKind.Unknown, null);

        if (type.ToDisplayString() == "System.Half") return (TKind.Half, TKind.Unknown, null);

        if (type is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_Byte })
            return (TKind.ByteArray, TKind.Unknown, null);

        if (type is INamedTypeSymbol named)
        {
            var origDisplay = named.OriginalDefinition.ToDisplayString();
            if ((origDisplay == "System.Collections.Generic.List<T>" ||
                 origDisplay == "System.Collections.Generic.IList<T>" ||
                 origDisplay == "System.Collections.Generic.ICollection<T>" ||
                 origDisplay == "System.Collections.Generic.IEnumerable<T>") &&
                named.TypeArguments.Length == 1)
            {
                var elem = named.TypeArguments[0];
                var (ek, _, _) = Classify(elem);
                return (TKind.List, ek, elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            if (named.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == SerializableAttr))
                return (TKind.Nested, TKind.Unknown, named.Name); // elemFull repurposed as the simple type name
        }

        return (TKind.Unknown, TKind.Unknown, null);
    }

    private static IMethodSymbol? FindRecordCtor(INamedTypeSymbol type, List<MemberInfo> members)
    {
        return type.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c => c.Parameters.All(p =>
                members.Any(m =>
                    string.Equals(m.MemberName, p.Name, System.StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(m.Key, p.Name, System.StringComparison.OrdinalIgnoreCase))));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static string? ReaderCall(TKind k) => k switch
    {
        TKind.Bool   => "reader.GetBoolean()",
        TKind.SByte  => "reader.GetSByte()",
        TKind.Short  => "reader.GetShort()",
        TKind.Int    => "reader.GetInteger()",
        TKind.Long   => "reader.GetLong()",
        TKind.Byte   => "reader.GetByte()",
        TKind.UShort => "reader.GetUShort()",
        TKind.UInt   => "reader.GetUInteger()",
        TKind.ULong  => "reader.GetULong()",
        TKind.Half   => "reader.GetHalf()",
        TKind.Float  => "reader.GetSingle()",
        TKind.Double => "reader.GetDouble()",
        TKind.String => "reader.GetString()",
        TKind.ByteArray => "reader.GetByteArray()",
        _ => null
    };

    private static string DefaultExpr(TKind k) => k switch
    {
        TKind.String    => "null!",
        TKind.ByteArray => "null!",
        TKind.List      => "null!",
        TKind.Nested    => "null!",
        TKind.NullablePrimitive => "null",
        _ => "default"
    };

    private static string Pad(int indent) => new string(' ', indent * 4);

    private static string Escape(string s) =>
        s.Replace('.', '_').Replace('<', '_').Replace('>', '_')
         .Replace(' ', '_').Replace(',', '_').Replace(':', '_').Replace('+', '_');

    // Strip "global::" prefix for use in "new X()" expressions
    private static string Strip(string s) => s.StartsWith("global::") ? s.Substring(8) : s;

    // -------------------------------------------------------------------------
    // Data model (plain class instead of record for netstandard2.0 compat)
    // -------------------------------------------------------------------------

    private sealed class MemberInfo
    {
        public string  MemberName    { get; }
        public string  Key           { get; }
        public TKind   Kind          { get; }
        public string  FullTypeName  { get; }
        public TKind   ElemKind      { get; }
        public string? ElemFullTypeName { get; }

        public MemberInfo(string memberName, string key, TKind kind, string fullTypeName,
            TKind elemKind, string? elemFullTypeName)
        {
            MemberName      = memberName;
            Key             = key;
            Kind            = kind;
            FullTypeName    = fullTypeName;
            ElemKind        = elemKind;
            ElemFullTypeName = elemFullTypeName;
        }
    }
}
